#!/bin/sh

# In EFI using the EFI version of mkconfig (if available)
if [ -d /sys/firmware/efi ] && which grub2-efi-mkconfig >/dev/null 2>&1; then
	grub_mkconfig=grub2-efi-mkconfig
else
	grub_mkconfig=grub2-mkconfig
fi
$grub_mkconfig -o /boot/grub2/grub.cfg
